services:
  - type: web
    name: cde-desprendibles
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: gunicorn app:app
